[package]
name = "bifrost-quirk"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
bifrost-core.workspace = true
bifrost-transport.workspace = true
quirk = { path = "../../../../quirk" }
thiserror.workspace = true

[dev-dependencies]
bifrost-iroh.workspace = true
tokio.workspace = true

[lints]
workspace = true
