[package]
publish = false  # git-only for now, not published to crates.io
name = "bifrost-quirk"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
bifrost-core.workspace = true
bifrost-transport.workspace = true
quirk = { git = "https://github.com/theia-hq/quirk", rev = "73bf620ceb6a3b630a1bd38a4d8fef48ee595a79" }
thiserror.workspace = true

[dev-dependencies]
bifrost-iroh.workspace = true
tokio.workspace = true

[lints]
workspace = true
