[package]
name = "bifrost-conformance"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
bifrost.workspace = true
tokio.workspace = true

[dev-dependencies]
bifrost-iroh.workspace = true
bifrost-mem.workspace = true
bifrost-quirk.workspace = true

[lints]
workspace = true
